- name: Deploy Spring Boot App locally
  hosts: localhost
  become: false
  gather_facts: true

  vars:
    target_dir: "/home/naman-chhabra/app"

  tasks:
    - name: Create deployment directory
      file:
        path: "{{ target_dir }}"
        state: directory
        mode: '0755'

    - name: Stop running Spring Boot app if any
      shell: |
        if pgrep -f task-manager.jar; then
          pkill -f task-manager.jar
        fi
      ignore_errors: true


    - name: Copy JAR file to deployment directory
      copy:
        src: /var/lib/jenkins/workspace/task-manager-pipeline/target/task-manger-0.0.1-SNAPSHOT.jar
        dest: "{{ target_dir }}/task-manager.jar"
        mode: '0755'
        remote_src: true

    - name: Start Spring Boot app
      shell: nohup java -jar {{ target_dir }}/task-manager.jar --server.port=8081 > {{ target_dir }}/app.log 2>&1 &
      async: 10
      poll: 0
